# Generated by Django 4.2 on 2024-09-18 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('region', models.CharField()),
                ('district', models.CharField()),
                ('floor', models.IntegerField()),
                ('room', models.CharField()),
                ('description', models.TextField()),
                ('phone', models.CharField()),
                ('main_img', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('img1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('img2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('threemonrent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sixmonrent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ninemonrent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_listed', models.BooleanField()),
            ],
        ),
    ]
