# Generated by Django 4.2 on 2024-09-19 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_alter_warehouse_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='region',
            field=models.CharField(choices=[('Hong Kong Island', 'Hong Kong Island'), ('New Territories', 'New Territories'), ('Kowloon', 'Kowloon')], max_length=50),
        ),
    ]
