# Generated by Django 4.2 on 2024-09-29 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0005_alter_warehouse_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
