# Generated by Django 4.2 on 2024-09-29 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0006_warehouse_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouse',
            name='slug',
        ),
    ]
