# Generated by Django 4.2 on 2024-09-29 15:47

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0007_remove_warehouse_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='title', unique=True),
        ),
    ]
