# Generated by Django 4.2 on 2024-09-29 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0008_warehouse_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
