# Generated by Django 4.2 on 2024-09-30 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0009_alter_warehouse_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='building',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='street',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
