# Generated by Django 4.2 on 2024-09-18 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer',
            name='transfer_id',
        ),
    ]
