# Generated by Django 4.2 on 2024-09-18 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
                ('first_name', models.CharField()),
                ('last_name', models.CharField()),
                ('creation_date', models.DateTimeField()),
                ('main_img', models.ImageField(upload_to='')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
